[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/admission-chat"
  status = 301

[[redirects]]
  from = "/admission-chat/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/admission-chat/*"
  to = "/index.html"
  status = 200
